// Shared language list — global coverage. The 2-letter `code` is what both
// backend (`preferred_language`) and frontend use. `uiTranslated: true` marks
// the codes that have full `TRANSLATIONS` bundles in App.jsx. For the rest, the
// voice works (backend system prompt maps every code here via _lang_names /
// LANGUAGE_NAMES), but the interface stays in English until a bundle lands.

export const LANGUAGES = [
  { code: 'en',  flag: '🇬🇧', label: 'English',    native: 'English',    uiTranslated: true },
  { code: 'fr',  flag: '🇫🇷', label: 'French',     native: 'Français',   uiTranslated: true },
  { code: 'ar',  flag: '🇸🇦', label: 'Arabic',     native: 'العربية',    uiTranslated: true },
  { code: 'es',  flag: '🇪🇸', label: 'Spanish',    native: 'Español',    uiTranslated: true },
  { code: 'de',  flag: '🇩🇪', label: 'German',     native: 'Deutsch',    uiTranslated: true },
  { code: 'ja',  flag: '🇯🇵', label: 'Japanese',   native: '日本語',       uiTranslated: true },
  { code: 'zh',  flag: '🇨🇳', label: 'Chinese',    native: '中文',        uiTranslated: true },
  { code: 'ko',  flag: '🇰🇷', label: 'Korean',     native: '한국어',       uiTranslated: true },
  { code: 'hi',  flag: '🇮🇳', label: 'Hindi',      native: 'हिन्दी',      uiTranslated: true },
  { code: 'pt',  flag: '🇧🇷', label: 'Portuguese', native: 'Português',  uiTranslated: true },
  { code: 'it',  flag: '🇮🇹', label: 'Italian',    native: 'Italiano',   uiTranslated: true },
  { code: 'nl',  flag: '🇳🇱', label: 'Dutch',      native: 'Nederlands', uiTranslated: true },
  { code: 'ru',  flag: '🇷🇺', label: 'Russian',    native: 'Русский',    uiTranslated: true },
  { code: 'tr',  flag: '🇹🇷', label: 'Turkish',    native: 'Türkçe',     uiTranslated: true },
  { code: 'pl',  flag: '🇵🇱', label: 'Polish',     native: 'Polski',     uiTranslated: true },
  { code: 'id',  flag: '🇮🇩', label: 'Indonesian', native: 'Indonesia',  uiTranslated: true },
  { code: 'uk',  flag: '🇺🇦', label: 'Ukrainian',  native: 'Українська' },
  { code: 'vi',  flag: '🇻🇳', label: 'Vietnamese', native: 'Tiếng Việt' },
  { code: 'th',  flag: '🇹🇭', label: 'Thai',       native: 'ไทย'         },
  { code: 'ms',  flag: '🇲🇾', label: 'Malay',      native: 'Melayu'    },
  { code: 'fa',  flag: '🇮🇷', label: 'Persian',    native: 'فارسی'     },
  { code: 'he',  flag: '🇮🇱', label: 'Hebrew',     native: 'עברית'     },
  { code: 'el',  flag: '🇬🇷', label: 'Greek',      native: 'Ελληνικά'  },
  { code: 'sv',  flag: '🇸🇪', label: 'Swedish',    native: 'Svenska'   },
  { code: 'no',  flag: '🇳🇴', label: 'Norwegian',  native: 'Norsk'     },
  { code: 'da',  flag: '🇩🇰', label: 'Danish',     native: 'Dansk'     },
  { code: 'fi',  flag: '🇫🇮', label: 'Finnish',    native: 'Suomi'     },
  { code: 'cs',  flag: '🇨🇿', label: 'Czech',      native: 'Čeština'   },
  { code: 'hu',  flag: '🇭🇺', label: 'Hungarian',  native: 'Magyar'    },
  { code: 'ro',  flag: '🇷🇴', label: 'Romanian',   native: 'Română'    },
  { code: 'bg',  flag: '🇧🇬', label: 'Bulgarian',  native: 'Български' },
  { code: 'hr',  flag: '🇭🇷', label: 'Croatian',   native: 'Hrvatski'  },
  { code: 'sk',  flag: '🇸🇰', label: 'Slovak',     native: 'Slovenčina'},
  { code: 'sr',  flag: '🇷🇸', label: 'Serbian',    native: 'Српски'    },
  { code: 'bn',  flag: '🇧🇩', label: 'Bengali',    native: 'বাংলা'     },
  { code: 'ta',  flag: '🇮🇳', label: 'Tamil',      native: 'தமிழ்'      },
  { code: 'te',  flag: '🇮🇳', label: 'Telugu',     native: 'తెలుగు'    },
  { code: 'mr',  flag: '🇮🇳', label: 'Marathi',    native: 'मराठी'      },
  { code: 'gu',  flag: '🇮🇳', label: 'Gujarati',   native: 'ગુજરાતી'   },
  { code: 'ur',  flag: '🇵🇰', label: 'Urdu',       native: 'اردو'       },
  { code: 'sw',  flag: '🇰🇪', label: 'Swahili',    native: 'Kiswahili' },
  { code: 'fil', flag: '🇵🇭', label: 'Filipino',   native: 'Filipino'  },
  { code: 'af',  flag: '🇿🇦', label: 'Afrikaans',  native: 'Afrikaans' },
  { code: 'ca',  flag: '🇪🇸', label: 'Catalan',    native: 'Català'    },
]
